"use client";

import { Palette, ShieldCheck } from "lucide-react";
import { useTheme } from "next-themes";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ThemeToggle } from "@/components/theme-toggle";

export default function SettingsPage() {
  const { theme } = useTheme();
  const themeLabel = theme === "dark" ? "Dark" : theme === "light" ? "Light" : "System";
  return <div className="space-y-5"><header><p className="text-sm font-medium uppercase tracking-[0.18em] text-primary">Workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Settings</h1><p className="mt-1 text-muted-foreground">A few quiet controls for your FinPilot experience.</p></header><div className="grid max-w-4xl gap-5 lg:grid-cols-2"><Card><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary text-secondary-foreground"><Palette className="h-4 w-4" /></div><div><CardTitle className="text-lg">Appearance</CardTitle><CardDescription>Choose how the workspace feels.</CardDescription></div></div></CardHeader><CardContent><div className="flex items-center justify-between rounded-xl border bg-muted/30 p-4"><div><p className="font-medium">Theme</p><p className="mt-1 text-sm text-muted-foreground">Currently using {themeLabel.toLowerCase()} mode.</p></div><ThemeToggle /></div></CardContent></Card><Card><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary text-secondary-foreground"><ShieldCheck className="h-4 w-4" /></div><div><CardTitle className="text-lg">Privacy & security</CardTitle><CardDescription>Your workspace is self-hosted.</CardDescription></div></div></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">FinPilot keeps your financial records in your configured local database. Authentication and account ownership checks are handled server-side.</p></CardContent></Card></div><Card className="max-w-4xl"><CardHeader><CardTitle className="text-lg">About FinPilot</CardTitle><CardDescription>Personal finance, kept understandable.</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2"><div className="rounded-xl bg-muted/40 p-4"><p className="text-muted-foreground">Version</p><p className="mt-1 font-medium">1.0.0</p></div><div className="rounded-xl bg-muted/40 p-4"><p className="text-muted-foreground">License</p><p className="mt-1 font-medium">MIT</p></div></CardContent></Card></div>;
}
