import { randomUUID } from "node:crypto";
import { relations } from "drizzle-orm";
import { boolean, jsonb, numeric, pgTable, text, timestamp } from "drizzle-orm/pg-core";

const id = (name: string) => text(name).primaryKey().$defaultFn(() => randomUUID());
const created = (name: string) => timestamp(name, { withTimezone: true, mode: "date" });

export const accountTypeValues = ["checking", "savings", "credit", "cash", "investment"] as const;
export const categoryTypeValues = ["income", "expense"] as const;
export const messageRoleValues = ["user", "assistant"] as const;
export const userRoleValues = ["user", "admin"] as const;

export const users = pgTable("users", { id: id("id"), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").notNull().default(false), image: text("image"), passwordHash: text("password_hash"), role: text("role").notNull().default("user"), createdAt: created("created_at").notNull().defaultNow(), updatedAt: created("updated_at").notNull().defaultNow() });
export const sessions = pgTable("session", { id: id("id"), expiresAt: created("expires_at").notNull(), token: text("token").notNull().unique(), createdAt: created("created_at").notNull().defaultNow(), updatedAt: created("updated_at").notNull().defaultNow(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }) });
export const authAccounts = pgTable("auth_account", { id: id("id"), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: created("access_token_expires_at"), refreshTokenExpiresAt: created("refresh_token_expires_at"), scope: text("scope"), password: text("password"), createdAt: created("created_at").notNull().defaultNow(), updatedAt: created("updated_at").notNull().defaultNow() });
export const verification = pgTable("verification", { id: id("id"), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: created("expires_at").notNull(), createdAt: created("created_at").notNull().defaultNow(), updatedAt: created("updated_at").notNull().defaultNow() });
export const accounts = pgTable("accounts", { id: id("id"), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), name: text("name").notNull(), type: text("type").notNull(), balance: numeric("balance", { precision: 18, scale: 2 }).notNull().default("0"), currency: text("currency").notNull().default("USD"), createdAt: created("created_at").notNull().defaultNow(), updatedAt: created("updated_at").notNull().defaultNow() });
export const categories = pgTable("categories", { id: id("id"), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), name: text("name").notNull(), color: text("color").notNull(), icon: text("icon"), type: text("type").notNull(), createdAt: created("created_at").notNull().defaultNow(), updatedAt: created("updated_at").notNull().defaultNow() });
export const transactions = pgTable("transactions", { id: id("id"), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: text("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }), categoryId: text("category_id").notNull().references(() => categories.id, { onDelete: "restrict" }), amount: numeric("amount", { precision: 18, scale: 2 }).notNull(), date: created("date").notNull(), description: text("description").notNull(), isRecurring: boolean("is_recurring").notNull().default(false), createdAt: created("created_at").notNull().defaultNow(), updatedAt: created("updated_at").notNull().defaultNow() });
export const chatSessions = pgTable("chat_sessions", { id: id("id"), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: text("title").notNull().default("New Chat"), createdAt: created("created_at").notNull().defaultNow(), updatedAt: created("updated_at").notNull().defaultNow() });
export const chatMessages = pgTable("chat_messages", { id: id("id"), sessionId: text("session_id").notNull().references(() => chatSessions.id, { onDelete: "cascade" }), role: text("role").notNull(), content: text("content").notNull(), toolCalls: jsonb("tool_calls"), chartSpec: jsonb("chart_spec"), createdAt: created("created_at").notNull().defaultNow() });
export const importLogs = pgTable("import_logs", { id: id("id"), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), filename: text("filename").notNull(), rowCount: text("row_count").notNull(), successCount: text("success_count").notNull(), errorCount: text("error_count").notNull(), errors: jsonb("errors"), createdAt: created("created_at").notNull().defaultNow() });
export const adminAuditLogs = pgTable("admin_audit_logs", { id: id("id"), actorId: text("actor_id").notNull().references(() => users.id, { onDelete: "cascade" }), action: text("action").notNull(), targetType: text("target_type").notNull(), targetId: text("target_id"), result: text("result").notNull(), metadata: jsonb("metadata"), createdAt: created("created_at").notNull().defaultNow() });

export const usersRelations = relations(users, ({ many }) => ({ accounts: many(accounts), categories: many(categories), transactions: many(transactions), chatSessions: many(chatSessions), importLogs: many(importLogs), adminAuditLogs: many(adminAuditLogs), sessions: many(sessions), authAccounts: many(authAccounts) }));
export const sessionsRelations = relations(sessions, ({ one }) => ({ user: one(users, { fields: [sessions.userId], references: [users.id] }) }));
export const authAccountsRelations = relations(authAccounts, ({ one }) => ({ user: one(users, { fields: [authAccounts.userId], references: [users.id] }) }));
export const accountsRelations = relations(accounts, ({ one, many }) => ({ user: one(users, { fields: [accounts.userId], references: [users.id] }), transactions: many(transactions) }));
export const categoriesRelations = relations(categories, ({ one, many }) => ({ user: one(users, { fields: [categories.userId], references: [users.id] }), transactions: many(transactions) }));
export const transactionsRelations = relations(transactions, ({ one }) => ({ user: one(users, { fields: [transactions.userId], references: [users.id] }), account: one(accounts, { fields: [transactions.accountId], references: [accounts.id] }), category: one(categories, { fields: [transactions.categoryId], references: [categories.id] }) }));
export const chatSessionsRelations = relations(chatSessions, ({ one, many }) => ({ user: one(users, { fields: [chatSessions.userId], references: [users.id] }), messages: many(chatMessages) }));
export const chatMessagesRelations = relations(chatMessages, ({ one }) => ({ session: one(chatSessions, { fields: [chatMessages.sessionId], references: [chatSessions.id] }) }));
export const importLogsRelations = relations(importLogs, ({ one }) => ({ user: one(users, { fields: [importLogs.userId], references: [users.id] }) }));
export const adminAuditLogsRelations = relations(adminAuditLogs, ({ one }) => ({ actor: one(users, { fields: [adminAuditLogs.actorId], references: [users.id] }) }));
